### ISSUE TITLE
Each call can return different number of devices

### ISSUE THREAD

**Issue by genifycom** [novotnyllc/Zeroconf#104]
I am using your sample call:

public async Task EnumerateAllServicesFromAllHosts()
{
    ILookup<string, string> domains = await ZeroconfResolver.BrowseDomainsAsync();            
    var responses = await ZeroconfResolver.ResolveAsync(domains.Select(g => g.Key));            
    foreach (var resp in responses)
        Console.WriteLine(resp);
}

The number of devices changes between calls. What is the recommended way to see if all devices were reported? Do you have any example code?

Thanks

**Comment by fgheysels** [comment]
I am experiencing the same issue.
I'm running the `ResolveAsync` in a loop and have a delay of 5 sec's between each call.  The result of the ResolveAsync call is not consistent; sometimes 4 devices are discovered, sometimes 5, 6, 7...

However, 3 devices are always resolved.  How is this possible ?

**Comment by clairernovotny** [comment]
This is all dependent on the behavior of the other devices on the network. Not much we can do here.
