### ISSUE TITLE
ZeroConf for IOS seems to be broken (for networks without a default gateway)?

### ISSUE THREAD

**Issue by Samureimer** [novotnyllc/Zeroconf#111]
We've had ZeroConf running on IOS and Windows without any issues for quite some time.
About a month ago the discovery stopped working entirely.
What seems to be the issue is that when connected to a WIFI network with no default gateway the socket.Bind(endpoint) makes the Iphone stop receiving the multicast packages from that network.
[Commenting out this line makes the App work again.](https://github.com/onovotny/Zeroconf/blob/7037b8edc3a7ade0ca5650ba69bf048112308c67/Zeroconf/NetworkInterface.cs#L107)

I have observed in Wireshark that the request is sent onto the network and the device responds as expected. What I haven't been able to do is to find out why this filters out the packages.

@onovotny or anyone else, can you verify this?

A quick way to test this is to configure the IPhones IP to manual and give it same address as given from the DHCP server but don't add the gateway of course.

**Comment by onovotny** [comment]
Can you raise an issue with Xamarin https://github.com/xamarin/xamarin-macios. That's probably the best place to get an answer if there's a bug with the iOS version or the platform.

**Comment by Samureimer** [comment]
Of course. But I imagine that it will take quite some time before this is fixed.
Would you we willing to accept a pull request where we don't filter the packages through socket binding but do it via the remote endpoint after the package has been received? [A 5353 port mach would be checked here](https://github.com/onovotny/Zeroconf/blob/7037b8edc3a7ade0ca5650ba69bf048112308c67/Zeroconf/NetworkInterface.cs#L130)

If not we have to fork your repository and implement the fix our selves as we need a fix rather quickly. Do you see any problem in doing the filtration this way?

**Comment by Samureimer** [comment]
Sorry for the long delay.
This is the solution that i'm proposing:
[Don't bind to a specific port](https://github.com/Samureimer/Zeroconf/blob/6c8dd00f286a680408d9d507d61d6ec9b2f0d84d/Zeroconf/NetworkInterface.cs#L107)
[Filter the ports here instead](https://github.com/Samureimer/Zeroconf/blob/6c8dd00f286a680408d9d507d61d6ec9b2f0d84d/Zeroconf/NetworkInterface.cs#L130)

**Comment by omghb** [comment]
I ran into a similar issue which might be related to this one.

When I have connected my iPad to the Mac then I do not receive multicast UDP traffic. At least for networks that have no Gateway. As soon as I cut the connection between iPad and Mac then I'm able to see services via ZeroConf over Wi-Fi again.

* I believe the connection between iPad and Mac has some influence on receiving multicast UDP traffic. 
* I tried the workarounds provided by @Samureimer but they didn't solve my issue.

Versions:
* iPad: 13.2.3
* Mac: 10.15.1 (Catalina) with Xcode 11.2.1

**Comment by Samureimer** [comment]
@omghb It didn't work for us either in the end.
We were fortunate that we could fix the problem by providing a default gateway on the network.

As I recall from my testing in January it seems to be a problem in .Net, but im not entirely sure.
We still rarely have problems detecting devices on Windows, but **ONLY** on a WIFI network (With a default gateway).
Resetting the network adapter resolves the issue.
I'll let you know if we ever find a proper fix.

**Comment by clairernovotny** [comment]
Closing due to age. Happy to take a PR if applicable.
