### ISSUE TITLE
Cancelling ResolveAsync causes use of disposed object errors

### ISSUE THREAD

**Issue by codaris** [novotnyllc/Zeroconf#114]
Cancelling the ResolveAsync() through the cancellation token causes a bunch of exceptions related to the use of disposed socket instances, etc.

Similarly, calling Dispose() on the IObservable subscription to cancel that also does not work.

The code I'm working on tries to about the ResolveAsync() as soon as it finds a matching host.

**Comment by onovotny** [comment]
I believe those are first-chance exceptions and not unhandled, correct?

If so, there's no clean way to cancel that doesn't do that but it shouldn't affect any calling code. I'm happy to take a PR once the underlying API's evolve to provide a better option.

**Comment by codaris** [comment]
They flow through to my ` TaskScheduler.UnobservedTaskException` exception handler so they are unhandled.  About 6 or so exceptions are triggered when the ResolveAsync() is cancelled.

**Comment by onovotny** [comment]
Unobserved task exceptions don't kill the process; they haven't since .NET 4.

**Comment by codaris** [comment]
They do not terminate the process but we use UnobservedTaskException to find actual issues in background task code.  A library shouldn't just be using disposed objects and expecting users to ignore the resulting exceptions.  

If you cannot avoid using a disposed object -- which to me is a code smell -- a few well placed exception handlers or ContinueWith() could swallow the exceptions.  If I end up with some time, I'll take a look.

**Comment by onovotny** [comment]
The trouble is that `UdpClient`'s `SendAsync` and `RecieveAsync` doesn't have an overload with a cancellation token. That means when things are canceled, we have to hard-dispose the socket

https://github.com/onovotny/Zeroconf/blob/master/Zeroconf/NetworkInterface.cs#L127

https://github.com/onovotny/Zeroconf/blob/master/Zeroconf/NetworkInterface.cs#L154

It's possible that we can avoid the rethrow here https://github.com/onovotny/Zeroconf/blob/master/Zeroconf/NetworkInterface.cs#L170 when `shouldCancel` is `true` though I haven't had time to look.

**Comment by codaris** [comment]
I see!

Question: have you tried closing the socket with Close() rather than disposing it in the case of cancellation?  It seems that's the more common solution to the problem of "cancelling" those async methods.  It might not solve the issue, just change it, but the exceptions I got were all related to Dispose().

**Comment by clairernovotny** [comment]
Closing due to age.
