### ISSUE TITLE
Zeroconf not working in Release version of Xamarin.Android

### ISSUE THREAD

**Issue by mu88** [novotnyllc/Zeroconf#115]
I'm using your package in my Android app, written with Xamarin.Android. During development with USB debugging, Zeroconf is working perfectly fine. But after building the app with Azure DevOps in Release configuration and installing the APK, it doesn't find any devices.

I've expected that Android would ask me during installation about the Wifi Multicast state permission, but it doesn't. Is this correct?

The package is added as a `PackageReference` to my Xamarin project.

**Comment by clairernovotny** [comment]
Closing due to age.
