### ISSUE TITLE
Disposing client inside loop in NetworkRequestAsync()

### ISSUE THREAD

**Issue by alexbk66** [novotnyllc/Zeroconf#116]
I'm not sure about this, that's why asking.

Inside the "for" loop we dispose the client, so second try will try to use disposed client. Hence the exceptions "Can't access disposed object":

`((IDisposable)client).Dispose();`

So my guess is - the "for" line and "using" line should be swapped:
```
for (var i = 0; i < retries; i++)
//??using (var client = new UdpClient())
{
    //??for (var i = 0; i < retries; i++)
    using (var client = new UdpClient())
    {
```

**Comment by clairernovotny** [comment]
Closing due to age.
