### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x20 in tid 24149 (Thread Pool Wor)

### ISSUE THREAD

**Issue by RickTracer** [novotnyllc/Zeroconf#125]
Hi, I'm getting an issue similar to https://github.com/onovotny/Zeroconf/issues/8

I'm just deploying the barest of code, using Xamarin examples in Visual Studio 2019 as well as taking this project from GIT and deploying the test cases. Both the BrowseDomainsAsync and ResolveAsync throw this. It seems to be at the end of the timeout, I can see that it did some work because in the debug I get some results before the crash. If I increase the timeout it takes longer for the SIGSEGV to happen.

[0:] IP: 192.168.0.45, Bytes: 46, IsResponse: False
[0:] IP: 192.168.0.1, Name: _http, Bytes: 190, IsResponse: True
[0:] IP: 192.168.0.1, Name: _http, Bytes: 190, IsResponse: True
[0:] IP: 192.168.0.29, Name: _http, Bytes: 108, IsResponse: True
[0:] IP: 192.168.0.60, Name: _workstation, Bytes: 227, IsResponse: True
[0:] IP: 192.168.0.12, Name: _pdl-datastream, Bytes: 203, IsResponse: True
[0:] IP: 192.168.0.45, Bytes: 219, IsResponse: False
[0:] IP: 192.168.0.45, Name: Android-2, Bytes: 502, IsResponse: True
[0:] IP: 192.168.0.12, Name: _http, Bytes: 65, IsResponse: True
Thread finished: <Thread Pool> #8
The thread 0x8 has exited with code 0 (0x0).
[0:] Done Scanning

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
06-16 18:59:31.539 E/mono-rt (24058): /proc/self/maps:

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x7ee7485678):0x7ee7485668  00 1c 
40 b9 c0 03 5f d6 fd 7b bf a9 fd 03 00 91  ..@..._..{......
0x7ee7485678  08 20 40 b9 a8 00 c8 37 88 01 e0 37 00 00 40 f9  . @....7...7..@.
0x7ee7485688  fd 7b c1 a8 c0 03 5f d6 60 08 00 b0 01 0a 00 f0  .{...._.`.......
0x7ee7485698  03 0a 00 f0 00 24 06 91 21 80 08 91 63 8c 0a 91  .....$..!...c...

No native Android stacktrace (see debuggerd output).

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Threading._ThreadPoolWaitCallback:PerformWaitCallback <0x00007>
	  at <Module>:runtime_invoke_bool <0x0006f>
=================================================================

<..snip..>

06-16 18:59:31.544 F/libc    (24058): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x20 in tid 24149 (Thread Pool Wor)

Any ideas? 

I tried to put "System;" in the "Ignore Assemblies" but the path to get there seems to have been re-worded in VS 2019 on Windows 10. I tried by Right Clicking ZeroconfTest.Xam.Android -> Properties -> Android Options and adding this in "Skip linking assemblies"

This fails on my Samsung S8 (Android 9.0 API 28) and my wife's Sony Experia Z (Android 8.0 API 26). On the Emulators it works ok and it _was_ working ok on my phone up till a few days ago (but Visual Studio 2019 had some updates and possibly since then it's not worked).

Thanks for any suggestions (I tried updating all NuGet packages as well as trying older versions, to no avail).

**Comment by RickTracer** [comment]
It seems I can fix this if I change :
catch when (Volatile.Read(ref shouldCancel))
                                                   {
                                                       // If we're canceling, eat any exceptions that come from here   
                                                   }

to a plain catch { } in NetworkRequestAsync method...

Is this something you can incorporate back please...? Thanks!

**Comment by anpin** [comment]
I'm also experiencing the same issue with VS2019 and XF 3.6.0.344457

**Comment by mu88** [comment]
Me too with VS 2019:
![image](https://user-images.githubusercontent.com/4560672/59921474-0f714a00-942e-11e9-9721-1cafa773816d.png)

**Comment by clairernovotny** [comment]
Closing due to age. Please reopen if still an issue with the latest Xamarin bits.
