### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by smoy** [novotnyllc/Zeroconf#15]
Does this library support IPv6? It seems like the network code always use a IPv4 multicast address.

https://github.com/onovotny/Zeroconf/blob/master/Zeroconf.NetFx/NetworkInterface.cs#L83

It seems like this implementation does not delegate to Android's http://developer.android.com/reference/android/net/nsd/NsdServiceInfo.html which support boths IPv4 and IPv6.

**Comment by onovotny** [comment]
There's no specific IPv6 support yet but I'm happy to take a PR :)

**Comment by smoy** [comment]
Yea, I am exploring a solution that address both IPv4 & IPv6 environment as iOS 9 app store submission soon requires IPv6 support (well at the very least it has to work under DNS64/NAT64). Looking at the current code architecture, the iOS & android platform dependency only involves socket operation. 

Both iOS & Android provides the entire ZeroConf stack, so to plug in those full stack implementation, it seems like quite a big refactoring in the current architecture.

**Comment by eziante** [comment]
I'm interested in the IPv6 support as well and I have tried to implement it already, but I have no way of testing it since I'm not able to compile it due to missing dependencies etc.

I've tried to add support for IPv6 as well as specifying what request you want (PTR, A, AAA, etc.)

**Comment by clairernovotny** [comment]
Closing due to age. Will take a PR if applicable.
