### ISSUE TITLE
Support for resolving only a subset of network interfaces 

### ISSUE THREAD

**Issue by wasehahmad** [novotnyllc/Zeroconf#155]
Can we add an optional parameter, and then support for, specifying an `IEnuerable<System.Net.NetworkInformation.NetworkInterface>`  to be resolved? If there are a lot of printers connected and we only want to send a request to some devices. This would be an alternative to currently
`System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()`

**Comment by notronrj** [comment]
I second this request.
Is this project still being worked on?

**Comment by clairernovotny** [comment]
Thanks, merged the PR.
