### ISSUE TITLE
Get Txt record from IReadOnlyList<IZeroconfHost>

### ISSUE THREAD

**Issue by SamihElsakhawi** [novotnyllc/Zeroconf#161]
Hi, i would like to know if is it possible to access the txt record  from:

`IReadOnlyList<IZeroconfHost> hosts = await ZeroconfResolver.ResolveAsync("_hid._udp.local.", scanTime);`

i want to get additional informations (like devide id), of the service.

Thank you.

Regards.

**Comment by notronrj** [comment]
Something like this:

`            IReadOnlyList<IZeroconfHost> results = await ZeroconfResolver.ResolveAsync("_bohaprinter._tcp.local.");

            for( int i=0; i < results.Count; i++ )
            {
                IZeroconfHost host = results[i];
                IReadOnlyDictionary<string, string> kvp = (IReadOnlyDictionary<string, string>)host.Services["_bohaprinter._tcp.local."].Properties[0];

                // The host.Id appears to have the IP address and an optional name.
                // So we strip off anything after : if it exists
                String id = host.Id.Split(':')[0];
                Debug.WriteLine($"ID:{id}  Note:{kvp["note"]}");
            }
        }`

**Comment by clairernovotny** [comment]
Closing due to age.
