### ISSUE TITLE
Alternative solution in NET-mDNS

### ISSUE THREAD

**Issue by davidzwa** [novotnyllc/Zeroconf#163]
I wanted to leave a tip for future finders of this repo:
A library called https://github.com/richardschneider/net-mdns exists, which is able to do #103 and more, and is more maintained (bug-wise and feature-wise). Second to that, it has many dependent repositories and very thorough testing. I found it easier to work with and it works more reliably (and faster, but that could be me).

Also looking at the unclosed issues around here, you might want to switch over.

@onovotny it is not my intention to bring any negative impact to your work. I hope you realise that I'm providing this tip with the best of intentions. I want to express appreciation for your efforts.

Also if the linked repo/package is structurally different or lacking in what it supports (os/arch), please tell me!

**Comment by HanVertegaal** [comment]
I have been using the repo you pointed to for some time. However, it no longer seems to be maintained and stuck at .NET 4.61. While looking for alternatives I found Zeroconf.

**Comment by clairernovotny** [comment]
I get releases out as needed. Most work is via PRs, and contributions are welcome.
