### ISSUE TITLE
Is it possible to get the hostname ?

### ISSUE THREAD

**Issue by pdgmdm** [novotnyllc/Zeroconf#166]
I am using the sample as provided in the documentation:

`using Zeroconf;
public async Task ProbeForNetworkPrinters()  
{  
    IReadOnlyList<IZeroconfHost> results = await  
        ZeroconfResolver.ResolveAsync("_printer._tcp.local.");  
}`

Is it possible to retrieve the hostname from IZeroconfHost ?

**Comment by clairernovotny** [comment]
Any data we get is returned in the existing records. You can also try doing a DNS lookup on the IP address if it's not available via Zeroconf.
