### ISSUE TITLE
Cannot install Zeroconf in UWP app

### ISSUE THREAD

**Issue by daltonclaybrook** [novotnyllc/Zeroconf#180]
I have a UWP app, but when I attempt to install the latest Zeroconf package using the NuGet package manager, I get the following error:

```
Package Zeroconf 3.4.2 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-x64-aot. Package Zeroconf 3.4.2 supports:
  - net46 (.NETFramework,Version=v4.6)
  - netstandard2.0 (.NETStandard,Version=v2.0)
```

Is there something I'm doing wrong? Disclaimer: I've fairly new to Windows development, so apologies if this is a user-error.

**Comment by clairernovotny** [comment]
You need to set the target platform version to at least 16299. The available API's are determined by the Target Platform Version and the Target Platform Min Version is the lowest version you support. You can see the support status of Win10 here: https://docs.microsoft.com/en-us/windows/release-information/

**Comment by clairernovotny** [comment]
Closing due to age.
