### ISSUE TITLE
How to create a mdns can be found

### ISSUE THREAD

**Issue by PhilanthropistBright** [novotnyllc/Zeroconf#186]

**Comment by SpencerBurgess** [comment]
You're wanting to create/broadcast an mDNS service that can then be discovered or you are trying to discover a service? If you side with the first part of that question then this is not the right library for that. A quick search brings up a project that may help you: [(https://github.com/richardschneider/net-mdns)](url)

For general usage/discovery check out the README for this project. For specific issues, add a description/comment and we can all try and help each other. 👍 :)

**Comment by clairernovotny** [comment]
Closing due to age. This project only supports querying/listening for mDNS records, not serving them.
