### ISSUE TITLE
Zeroconf.ResolveAsync does not find multiple service advertised from the same host

### ISSUE THREAD

**Issue by ChrisKays** [novotnyllc/Zeroconf#198]
First of all thank you for the library, it's really helpful.

I have a separate server app that publish ipps service to my local network - I use RegisterService from Mono.Zeroconf library (https://www.mono-project.com/archived/monozeroconf/), Services are published from  the same host using my server app.

Now I'm trying to use the Zeroconf.ResolveAsync to browse/retrieved the advertised services BUT only 1 service is returned per host.

Any help how I can retrieve all the ipps services advertised by the same host.

**Comment by hrbrgr** [comment]
Hi, I just noticed the same issue.
The reason for this being that Services announced from the same host get stored by their service name which is the name from the PTR record. Unfortunately this is e.g. _http._tcp if you announce a http server. (Have a look here: https://github.com/novotnyllc/Zeroconf/blob/8490eaddbbe516dc2bdc6f6392c5938734292a13/Zeroconf/ZeroconfResolver.cs#L145)
For a second http server there will be a second PTR record using _http._tcp.

When `AddService` (https://github.com/novotnyllc/Zeroconf/blob/b80f8cb9faabd9dd74d474c36cb57fedb5724424/Zeroconf/ZeroconfRecord.cs#L157) is called the first entry will be dropped when the second one is added. As they are get indexed by their name.

IMHO this is a bug, as the standard allows this

One could use e.g. `ptrRec.RR.RECORD.PTRDNAME` for indexing to avoid this problem
