### ISSUE TITLE
ZeroconfResolver.ResolveAsync not work on Xamarin IOS

### ISSUE THREAD

**Issue by neicureuil** [novotnyllc/Zeroconf#211]
Hi, 

I used ZeroconfResolver.ResolveAsync to resolve devices on my network with a Xamarin app.
On android all works fine but on IOS, the function return 0 results.
I have tried #195 solution with the change made on the github https://github.com/rcinge/Zeroconf/tree/bonjour_prototype but the same issue appear.

My error is :
`[0:] NotSearched: Errors {
    NSNetServicesErrorCode = "-72008";
    NSNetServicesErrorDomain = 10;
}`

On IOS is it need more thing to work ?
Can you help me ? 
Thanks

**Comment by Paccos** [comment]
I second this. No results for me on iOS when using `ZeroConfResolver.ResolveAsync` but works fine on Android.

Strangely, observing `ZeroConfResolver.ResolveContinuous` _does_ resolve devices in my networks with a Xamarin app, while `ZeroConfResolver.Resolve` does not.

**Comment by thomas-niederreiner** [comment]
Unfortunately, I'm facing the same issue :(
Further, ResolveContinuous doesn't yield any results for me.
@neicureuil Could you pease provide more details on how you implemented this?

**Comment by ivanoikon** [comment]
> Hi,
> 
> I used ZeroconfResolver.ResolveAsync to resolve devices on my network with a Xamarin app. On android all works fine but on IOS, the function return 0 results. I have tried #195 solution with the change made on the github https://github.com/rcinge/Zeroconf/tree/bonjour_prototype but the same issue appear.
> 
> My error is : `[0:] NotSearched: Errors { NSNetServicesErrorCode = "-72008"; NSNetServicesErrorDomain = 10; }`
> 
> On IOS is it need more thing to work ? Can you help me ? Thanks

I faced the same issue. Simply add that properties to info.plist and compile them properly with service you want to discover. 

	<key>NSLocalNetworkUsageDescription</key>
	<string>Reason for using Bonjour that the user can understand</string>
	<key>NSBonjourServices</key>
	<array>
	    <string>_protocol._tcp.</string>
	</array>
