### ISSUE TITLE
No results under iOS16

### ISSUE THREAD

**Issue by thomas-niederreiner** [novotnyllc/Zeroconf#249]
Hi, looks like the lib isn't working properly under iOS16. I'm not able to find any results.
Is there anyone else facing the same issue?

**Comment by Zig1375** [comment]
I'm facing the same issue... Is there any solution from this?

**Comment by Kistarlan** [comment]
Same issue

**Comment by MarLoe** [comment]
I think this is related to #244 and fixed by #246 
@clairernovotny, is work on this repo gone stale? Do you need help maintaining this?

**Comment by Zig1375** [comment]
No, unfortunately that PR didn't help.

**Comment by riccardominato** [comment]
Same issue here. Is it possible to merge the PR that fix this?

**Comment by twofingerrightclick** [comment]
@riccardominato Will need to allow other maintainers. Currently I think @clairernovotny is the only maintainer with merge permission.

**Comment by vhugogarcia** [comment]
> I think this is related to #244 and fixed by #255 @clairernovotny, is work on this repo gone stale? Do you need help maintaining this?

Thanks @MarLoe for helping to solve this issue. I'm wondering if you have uploaded a new nuget package with support for iOS 16 including your changes. Or if you know a different workaround 👍🏻 please

**Comment by project-x51** [comment]
Was this every resolved? I'm seeing the same problem in IOS 17

**Comment by clairernovotny** [comment]
Fixed, will be on NuGet sometime tomorrow.
