### ISSUE TITLE
.NET Maui Version

### ISSUE THREAD

**Issue by project-x51** [novotnyllc/Zeroconf#265]
Hi,

I needed a .NET Maui version of Zeroconf with the latest (non merged) fixes in it so I created a fork and added a Zeroconf.Maui project and test projects.

I'm not sure how to merge it back into the main branch so its here if anyone wants access to it and knows how to do the merge.
https://github.com/project-x51/Zeroconf

Robin

**Comment by clairernovotny** [comment]
Thank you for this work, I've merged it in!
