### ISSUE TITLE
Library is not compatible with .NET 9.0

### ISSUE THREAD

**Issue by ArchieCoder** [novotnyllc/Zeroconf#266]
I have the error: "The requested protocol has not been configured into the system, or no implementation for it exists." in a .NET 9 project.

More specifically, the exception happens in NetworkInterface.cs line 69: var p = adapter.GetIPProperties().GetIPv4Properties();

        IReadOnlyList<IZeroconfHost> responses = new List<IZeroconfHost>();

        await Task.Run(async () =>
                       {
                           try
                           {
                               ILookup<string, string> domains = await ZeroconfResolver.BrowseDomainsAsync(default, 2, 2000, null, CancellationToken.None);

                               responses = await ZeroconfResolver.ResolveAsync(domains.Select(g => g.Key),
                                   cancellationToken: CancellationToken.None);
                           }
                           catch (Exception exception)
                           {
                           }
                       });

![image](https://github.com/user-attachments/assets/cc1f215f-66e0-4c48-a687-f663bbdc5322)

**Comment by piersdeseilligny** [comment]
Any luck solving this? It seems the library is pretty much abandoned, and i've been struggling to find a replacement that works with .NET 9.

**Comment by ArchieCoder** [comment]
@piersdeseilligny I'm afraid that the bug resides in .NET. .NET 9 is a nice to have at the moment, so not high priority. I suggest that you download the source and compile it, there is nothing fancy to do, it compiles as-is.

If my hypothesis about a bug in .NET 9, you can create a GitHub issue in .NET repo.

**Comment by pcullen1** [comment]
I'm having the exact same issue.

**Comment by clairernovotny** [comment]
I can certainly add a .NET 9 target and release an update if there's a fix

**Comment by piersdeseilligny** [comment]
Looking through various forks, it appears that the following change might be a fix?: https://github.com/novotnyllc/Zeroconf/commit/375fb82e1c8319c77f0fdec55aeca10ee1e7fd47
I'm not familiar enough with the library to know if it would break anything.

The same fork also implemented a fix for iOS 16 (which may also have an impact on Mac Catalyst, I'm unsure): https://github.com/novotnyllc/Zeroconf/commit/e099a9d872141fe7c23eb608739453e9a67fcace

**Comment by pcullen1** [comment]
All, the recent fix works for me. Thanks! When will it be available in nuget?

**Comment by clairernovotny** [comment]
This is fixed now in main and the latest CI build, which is always available here: `https://pkgs.dev.azure.com/clairernovotny/GitBuilds/_packaging/Zeroconf/nuget/v3/index.json`

**Comment by ArchieCoder** [comment]
Thank you @clairernovotny, very appreciated. Your lib rocks.

**Comment by clairernovotny** [comment]
I'd love to get confirmation that the latest version on the CI feed solves this for you before I publish it?

**Comment by ArchieCoder** [comment]
@clairernovotny No more crashes, I tested it. Thank you!
