### ISSUE TITLE
Error in Service Enumeration

### ISSUE THREAD

**Issue by mhl4tky** [novotnyllc/Zeroconf#28]
Hi,

I just tried Zeroconf for the first time, referenced it in an empty .Net 4.5 Forms project via Nuget. The only function I'm calling is the "EnumerateAllServicesFromAllHosts()" from within the Form's constructor.

I'm getting pretty random "A first chance exception of type 'System.ObjectDisposedException' occurred in mscorlib.dll" error messages. I'm on a pretty big network with lots of Bonjour services, Zeroconf is able to find _some_ but by far not all. Each time I start the program, the number of error messages is random, between 3 to 6. It seems that the number of discovered services is higher when I have less error messages.

Michael

**Comment by clairernovotny** [comment]
Closing due to age.
