### ISSUE TITLE
[Feature Request] - Registering a service on Xamarin.Android and/or Xamarin.iOS

### ISSUE THREAD

**Issue by has-taiar** [novotnyllc/Zeroconf#3]
Hi Oren, 

I am working on a project where I need to do peer to peer communications across Android and iOS, and I found this library. 
This seems perfect for what I want to do, but would need to add the ability to register new services as well as discovering them. 

Is it possible to add such a feature? I am happy to help out with the development, but I do not have much experience in this space, so I would need some guidance :)

Thanks heaps for the great effort 
Cheers
Has

**Comment by hgiritzer** [comment]
Service registration/publishing in Xamarin-based apps (iOS, Android, WinPhone) would be really nice!
I wonder if @andrei-tatar has found (will find) some time to implement this?

**Comment by andrei-tatar** [comment]
No I haven't. I abandoned the idea a long time ago.

**Comment by andymac4182** [comment]
Is there any other libraries anyone is aware of that offers allowing a service to be discovered?

**Comment by kzu** [comment]
Don't know if maybe Mono.Zeroconf did this? @abock?

**Comment by abock** [comment]
I never specifically ran Mono.Zeroconf on iOS or Android, but I don't see a reason why it wouldn't work on iOS, since Mono.Zeroconf uses Bonjour under the hood, which I know is available in iOS (or at least used to be).

I have no idea what is available on Android, but I doubt it's Avahi.

**Comment by forlayo** [comment]
I would like to have this feature, as after doing the implementation of my app with this library and having it running really well I've noticed about this limitation xD

**Comment by clairernovotny** [comment]
Closing due to age.
