### ISSUE TITLE
iOS invalid operation exception when doing Resolve() with both cell data and WIFI turned on.

### ISSUE THREAD

**Issue by jeremycookhp** [novotnyllc/Zeroconf#55]
We are seeing an exception being thrown in ZeroConf 2.7.1 on iOS when we try to do a Resolve() when connected to both a WIFI network and have cell data enabled.   This doesn't seem to happen on all devices, and unfortunately it doesn't reproduce on my personal device that I am debugging on.   I captured an exception trace of this from another device, and here's what we see:

InvalidOperationException: Bind has already been called for this socket
      at System.Net.Sockets.Socket.set_ExclusiveAddressUse (Boolean value) <0x10108f570 + 0x00094> in <filename unknown>:0
  at System.Net.Sockets.UdpClient.set_ExclusiveAddressUse (Boolean value) <0x1010a1740 + 0x00027> in <filename unknown>:0
  at Zeroconf.NetworkInterface+<NetworkRequestAsync>d__1.MoveNext () <0x101d58b40 + 0x004ef> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---

On this particular device, if we then disable cell data, everything works normally.   I know this is not much to go off of, I had hoped to reproduce this with a debug version of ZeroConf to give more details, and will continue to try to do so.     We don't see this on Android at all.

Thanks
Jeremy

**Comment by onovotny** [comment]
One idea...if you use Rx and the ResolveContinuous methods, can you use error handling techniques to ignore those errors? http://introtorx.com/Content/v1.0.10621.0/11_AdvancedErrorHandling.html#AdvancedErrorHandling

**Comment by jeremycookhp** [comment]
Hey Oren,

More info for you.  I downloaded the master source and referenced it directly in my projects so I could see the ZeroConf debug output.

On iOS:

-          It is sending the Resolve() request across the cell adapter, as well as the WIFI adapter.   In this case, it resolves nothing on either adapter.  No errors /exceptions are generated, so the calls are all succeeding.    If I turn off cell data, I see it only scan the WIFI adapter, and then it starts returning results.   Important to note:  I am connected to a WIFI Access Point device, basically a device that broadcasts as a WIFI network, but it is the only device on that network.

-          Further debugging shows that the cell data adapter name is pdp-ip0, is of NetworkInterfaceType:Unknown(1), and apparently passes all the filters that check for multicast support, IPv4, etc.   I didn’t think that a cell connection supported multicast?   The WIFI adapter shows up as en0, is of NetworkInterfaceType:Ethernet(6).


On Android:

-          With cell data enabled, and with the same WIFI access point connected device, things work just fine.

-          Further debugging shows that when both the cell data and WIFI are enabled, the cell adapter isn’t even in the list of adapters .  So somehow android doesn’t even offer that up when connected via WIFI?   All adapters show a NetworkInterfaceType of 0, so maybe NetworkInterfaceType isn’t supported on Android.

-          When I disable WIFI, I then see the cell adapter show up.  But it gets filtered out as it doesn’t support Multicast.

So, is the intention that ZeroConf ignore the cell adapter?   I would certainly like it to do so on iOS as that is the cause of our failures.    Plus, there’s probably not much to really find of interest on the cell data connection anyway ;)

It would seem a possible fix to this would be to ignore adapters that report a NetworkInterfaceType of Unknown?

Thoughts?  Let me know if I can gather any more characterization info for you…

Thanks,
Jeremy

**Comment by jeremycookhp** [comment]
Hey Oren,

Well, I should have tested my suggested change first.  I tried filtering out the unknown device on iOS.  It then only scanned the WIFI connection, and it still failed to resolve my device.   So somehow being connected to cell data, and also to a WIFI access point device on iOS just isn't working.   I am at a loss to understand why this might be...

**Comment by Framnk** [comment]
We are also running into this issue with Zeroconf on an iPhone 6 device running iOS 10.  When using a ResolveAsync() from the Zeroconf mono package (version 2.7.2) it will throw an exception:

InvalidOperationException: Bind has already been called for this socket

I can also confirm that disabling cellular data as recommended by jeremycookhp does appear to allow things to work.

**Comment by onovotny** [comment]
@Framnk I'd be more than happy to accept a PR to fix this if you have any ideas how to filter out the cellular adapter for iOS. 

iOS, Android and .NET Core are all sharing the same code here:
https://github.com/onovotny/Zeroconf/blob/master/Zeroconf.DotNetCore/NetworkInterface.cs#L48-L75

There are checks there to try to ensure that only supported adapters are used but it's always possible there's an additional check that would help here.

**Comment by clairernovotny** [comment]
Closing due to age.
