### ISSUE TITLE
STOWED_EXCEPTION_System.Exception

### ISSUE THREAD

**Issue by ZeAleks** [novotnyllc/Zeroconf#66]
Hello there,

Some users of my application complains that it does not work. They say that the device I want to discover is not discovered.
I am not able to reproduce the problem.

But, the top one of exceptions generated by this application is :

STOWED_EXCEPTION_System.Exception_80072744_Zeroconf.dll!Zeroconf.NetworkInterface+__c__DisplayClass0_0._NetworkRequestAsync_b__0

Here is the stack trace :
Frame	Image	Function	Offset
0	Windows_ni	Windows.Networking.Sockets.DatagramSocketMessageReceivedEventArgs.GetDataReader	0x1	
1	Zeroconf_ni	Zeroconf.NetworkInterface+__c__DisplayClass0_0._NetworkRequestAsync_b__0	0x1A	

It is a Windows Phone 8.1 app.
I have no other informations.
Can you help me please ?

Thank you.
Alek

**Comment by onovotny** [comment]
I'm not really sure where this would be coming from without a repro

**Comment by clairernovotny** [comment]
Closing due to age.
