### ISSUE TITLE
Failed to run on Nougat android phones

### ISSUE THREAD

**Issue by enemaerke** [novotnyllc/Zeroconf#67]
This might be beyond your control, but just wanted to let you know. 

On Android 7 phones, the underlying way that you can obtain information on network adapters has changed so a number of properties (such as SupportsMulticast) always returns false. We are running on top of Xamarin and we see it in the Output as

> 11-14 15:04:44.665 W/_olufsen.OneApp(11974): type=1400 audit(0.0:5963): avc: denied { getattr } for path="/sys/class/net/r_rmnet_data6" dev="sysfs" ino=27642 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0
11-14 15:04:44.665 W/_olufsen.OneApp(11974): type=1400 audit(0.0:5964): avc: denied { getattr } for path="/sys/devices/virtual/net/r_rmnet_data5/flags" dev="sysfs" ino=27593 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
11-14 15:04:44.665 W/_olufsen.OneApp(11974): type=1400 audit(0.0:5965): avc: denied { getattr } for path="/sys/class/net/r_rmnet_data5" dev="sysfs" ino=27576 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0

From a bit of digging, this seems to be the root issue: https://bugzilla.xamarin.com/show_bug.cgi?id=44296

Xamarin/Mono has been updated with a fix in their current branch but as far as I can tell it has not been added to the Stable version. We ran into this issue and after some digging got things working by skipping the checks for SupportsMulticast and OperationalStatus (which are false and Unkown respectively) so we effectively scan more network adapters

Not sure if this warrants any action on your part, since at least Xamarin seems to be aware of this and is fixing it at some point.

**Comment by enantiomer2000** [comment]
I also have experienced this problem. I checked the developer.xamarin website and it says that issue 44296 will be incorporated into Xamarin 7.1 which is still in alpha. I don't feel like installing an alpha build (there is important work to be done) on my dev box so I will just wait:
https://developer.xamarin.com/releases/android/xamarin.android_7/xamarin.android_7.1/

**Comment by onovotny** [comment]
Is this still an issue? Can you confirm it's fixed for you with Android 7.1?

Thanks

**Comment by enemaerke** [comment]
I have not tested on Android 7.1 so unable to confirm, sorry.

**Comment by enantiomer2000** [comment]
7.1 is still has moved from beta to RC. We will test when it is finally released and report back.

**Comment by Matheus-Garbelini** [comment]
I've tested with 7.1 and it does not work. The debug output give errors like: 

```
02-16 19:19:49.248 W/App9.Droid( 5531): type=1400 audit(0.0:189): avc: denied { getattr } for uid=10126 path="/sys/devices/virtual/net/rmnet0/flags" dev="sysfs" ino=18710 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-16 19:19:49.248 W/App9.Droid( 5531): type=1400 audit(0.0:190): avc: denied { getattr } for uid=10126 path="/sys/class/net/rmnet0" dev="sysfs" ino=18693 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0
02-16 19:19:49.248 W/App9.Droid( 5531): type=1400 audit(0.0:191): avc: denied { getattr } for uid=10126 path="/sys/devices/virtual/net/dummy0/flags" dev="sysfs" ino=18632 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-16 19:19:49.248 W/App9.Droid( 5531): type=1400 audit(0.0:192): avc: denied { getattr } for uid=10126 path="/sys/class/net/dummy0" dev="sysfs" ino=18615 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0
02-16 19:19:49.248 W/App9.Droid( 5531): type=1400 audit(0.0:193): avc: denied { getattr } for uid=10126 path="/sys/devices/virtual/net/lo/flags" dev="sysfs" ino=6270 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-16 19:19:49.248 W/App9.Droid( 5531): type=1400 audit(0.0:194): avc: denied { getattr } for uid=10126 path="/sys/class/net/lo" dev="sysfs" ino=6253 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0
02-16 19:19:49.248 W/App9.Droid( 5531): type=1400 audit(0.0:195): avc: denied { getattr } for uid=10126 path="/sys/devices/fb000000.qcom,wcnss-wlan/net/p2p0/flags" dev="sysfs" ino=28322 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-16 19:19:49.248 W/App9.Droid( 5531): type=1400 audit(0.0:196): avc: denied { getattr } for uid=10126 path="/sys/class/net/p2p0" dev="sysfs" ino=28305 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0
02-16 19:19:49.248 W/App9.Droid( 5531): type=1400 audit(0.0:197): avc: denied { getattr } for uid=10126 path="/sys/devices/fb000000.qcom,wcnss-wlan/net/wlan0/flags" dev="sysfs" ino=28206 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-16 19:19:49.248 W/App9.Droid( 5531): type=1400 audit(0.0:198): avc: denied { getattr } for uid=10126 path="/sys/class/net/wlan0" dev="sysfs" ino=28189 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0
02-16 19:19:49.251 W/App9.Droid( 5531): type=1400 audit(0.0:199): avc: denied { getattr } for uid=10126 path="/sys/devices/virtual/net/ip6tnl0/flags" dev="sysfs" ino=23959 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-16 19:19:49.251 W/App9.Droid( 5531): type=1400 audit(0.0:200): avc: denied { getattr } for uid=10126 path="/sys/class/net/ip6tnl0" dev="sysfs" ino=23942 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0
02-16 19:19:49.251 W/App9.Droid( 5531): type=1400 audit(0.0:201): avc: denied { getattr } for uid=10126 path="/sys/devices/virtual/net/sit0/flags" dev="sysfs" ino=23893 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-16 19:19:49.251 W/App9.Droid( 5531): type=1400 audit(0.0:202): avc: denied { getattr } for uid=10126 path="/sys/class/net/sit0" dev="sysfs" ino=23876 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0
02-16 19:19:49.251 W/App9.Droid( 5531): type=1400 audit(0.0:203): avc: denied { getattr } for uid=10126 path="/sys/devices/virtual/net/usb0/flags" dev="sysfs" ino=20776 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-16 19:19:49.251 W/App9.Droid( 5531): type=1400 audit(0.0:204): avc: denied { getattr } for uid=10126 path="/sys/class/net/usb0" dev="sysfs" ino=20759 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0
02-16 19:19:49.251 W/App9.Droid( 5531): type=1400 audit(0.0:205): avc: denied { getattr } for uid=10126 path="/sys/devices/virtual/net/rev_rmnet8/flags" dev="sysfs" ino=19832 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-16 19:19:49.251 W/App9.Droid( 5531): type=1400 audit(0.0:206): avc: denied { getattr } for uid=10126 path="/sys/class/net/rev_rmnet8" dev="sysfs" ino=19815 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0
02-16 19:19:49.251 W/App9.Droid( 5531): type=1400 audit(0.0:207): avc: denied { getattr } for uid=10126 path="/sys/devices/virtual/net/rev_rmnet7/flags" dev="sysfs" ino=19766 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
02-16 19:19:49.251 W/App9.Droid( 5531): type=1400 audit(0.0:208): avc: denied { getattr } for uid=10126 path="/sys/class/net/rev_rmnet7" dev="sysfs" ino=19749 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=lnk_file permissive=0

```

**Comment by onovotny** [comment]
I would escalate to Xamarin...this is out of my control :/

**Comment by Matheus-Garbelini** [comment]
@onovotny UPDATE. It's working. turns out that i was using the incorrect version.
I'm using beta RC6 and its working. I just have one problem. Is i load again the 
```C++
responses = await ZeroconfResolver.BrowseDomainsAsync();
```
My application crashes with this error: 
```C++
02-16 22:59:52.582 F/libc    ( 6068): Fatal signal 6 (SIGABRT), code -6 in tid 6068 (App9.Droid)
02-16 22:59:52.613 F/libc    ( 6068): failed to resend signal during crash: Operation not permitted
```

Maybe I miss something with the "Zeroconf lock"? There's something to unload zeroconf to prevent this error?

**Comment by onovotny** [comment]
There's no way to avoid having to get the Android WiFiManager, getting a MultiCastLock and calling Acquire/Release.

How you do that in your app is up to you -- if you're using a PCL, then you might consider creating an interface that essentially does that. Otherwise you can use a Shared Code project and `#ifdef` it.

**Comment by Matheus-Garbelini** [comment]
@onovotny Thank you, I updated the comment.

**Comment by drobdymo** [comment]
It seems this is still an issue with Xamarin.Android 7.1. I receive the below error when trying to use the library on an HTC 10 running Nougat. Does anyone know of workarounds for this issue?

JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0x200001

**Comment by dusanders** [comment]
I am seeing the same error as drobdymo. The first run of ResolveAsync() works great, but the next call fails. I also get this output from monodroid-network: "Unable to determine interface 'rmnet_data1' state using Java API"
 followed by: "Failed to look up interface 'rmnet_data1' using Java API"

Seen on Google Pixel XL with Android 7.1

**Comment by clairernovotny** [comment]
Closing due to age.
