### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by Oliveirakun** [novotnyllc/Zeroconf#75]
Hi,
I'm trying to use the last version of zeroconf(2.8.0) in a project with Xamarin Forms and when I run the project and execute any code from zeroconf it shows this error: 

**System.BadImageFormatException - Could not resolve field token 0x0400000f**

Does anybody knows what's wrong?

Some info about my environment:
Xamarin Community Version: 6.2(build 1821)
Taget Profile: .NET portable - PCL 4.5 - Profile 259
IOS and Android project
Operational System: MacOs Sierra

**Comment by onovotny** [comment]
I would suggest filing an issue with Xamarin...not sure at all, sorry.

**Comment by Oliveirakun** [comment]
@onovotny Does it not work with PCL library (v4.5, Profile111) projects?

**Comment by onovotny** [comment]
It should...but you're not getting a NuGet restore/install error, you seem to be hitting some sort of runtime exception.

**Comment by Oliveirakun** [comment]
Ok, So I'm gonna use dependency services and develop a solution for each platform, thanks!

**Comment by clairernovotny** [comment]
Closing due to age.
