### ISSUE TITLE
IPv4 - The requested protocol has not been configured into the system, or no implementation for it exists

### ISSUE THREAD

**Issue by baks** [novotnyllc/Zeroconf#84]
I am getting following exception:

> System.Net.NetworkInformation.NetworkInformationException (0x80004005): The requested protocol has not been configured into the system, or no implementation for it exists
>    at System.Net.NetworkInformation.SystemIPInterfaceProperties.GetIPv4Properties()
>    at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__1.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 63
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Zeroconf.NetworkInterface.<NetworkRequestAsync>d__0.MoveNext() in C:\projects\zeroconf\Zeroconf.DotNetCore\NetworkInterface.cs:line 34
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Zeroconf.ZeroconfResolver.<ResolveInternal>d__4.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.cs:line 75
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Zeroconf.ZeroconfResolver.<ResolveAsync>d__15.MoveNext() in C:\projects\zeroconf\Zeroconf.Shared\ZeroconfResolver.Async.cs:line 73

I think adding extra check in [NetworkInterface](https://github.com/onovotny/Zeroconf/blob/dev/Zeroconf/Platforms/netstandard1.3/NetworkInterface.cs) class before quering for `IPv4Properties` will prevent from exception:

`adapter.Supports(NetworkInterfaceComponent.IPv4)` 

I can make PR for that if you agree that this is good solution.

**Comment by clairernovotny** [comment]
Closing due to age.
