### ISSUE TITLE
[Feature Request] Support unicast DNS

### ISSUE THREAD

**Issue by arion-p** [novotnyllc/Zeroconf#86]
In some cases it is usefule to also discover statically published services (which can also be non-local) over unicast DNS-SD

**Comment by arion-p** [comment]
Wanted to give it a try myself but I cannot build the solution from VS2017 (VS2015 does not recognize the project format of zeroconf.csproj).
Does it build in VS2017 or only MSBuild?

**Comment by clairernovotny** [comment]
The project requires VS 2019. Happy to take a PR if applicable, closing to to age otherwise.
