### ISSUE TITLE
Continous announcement for one service with new, changed, lost state (like bonjour)?

### ISSUE THREAD

**Issue by muffmolch** [novotnyllc/Zeroconf#89]
Hi
Just a short question. 
I saw the obervable resolver and announcement methods. They are great. But I need to track the changes of one service (to check if new instances spawns, get lost, chaged data, ...). 

```
            ServiceBrowser serviceBrowser = new ServiceBrowser();
            serviceBrowser.ServiceAdded += onServiceAdded;
            serviceBrowser.ServiceRemoved += onServiceRemoved;
            serviceBrowser.ServiceChanged += onServiceChanged;
```

would be very nice. But the observable methods are working for me also. 
Thus is it possible to get announcements only for ONE SPECIFIC service ("_blabla._udp._local.") with the information *new*, *lost*, *changed*?

**Comment by muffmolch** [comment]
really no one?

**Comment by muffmolch** [comment]
any changes?

**Comment by clairernovotny** [comment]
Closing due to age. I think you have what you need with observable -- just filter on the service you need?
