### ISSUE TITLE
Found ZeroconfHost ID is always equal to the IP address

### ISSUE THREAD

**Issue by SebastianBone** [novotnyllc/Zeroconf#94]
Hey,

I have the issue that all hosts that are found by ZeroconfResolver have no unique ID.
The ID is always equal to the IP address. So the ID will be changed when something changes on the IP so I have no secure way to identificate the host.
I tested this on different services and devices. (Xamarin Android and iOS)

Cheers
Sebastian

**Comment by onovotny** [comment]
Given that Zeroconf is a multi-cast DNS-based discovery-based mechanism, and hosts can choose what records to send back, there's not thing really secure about it. You can have other hosts on the subnet respond and "lie". 

What's the scenario here, what are you looking to do?

**Comment by SebastianBone** [comment]
Hey thanks for your quick respond,

i'm not concerned about the security but I need to get the Hostname / DNS Name resolved.
The scenario:
- I have a device that has an own hotspot
- I connect with my mobile on the hotspot
- ZeroConf gives me 192.168.1.1 as IP and ID
- I send a http request on the device that it should connect to my home network
- I change with the mobile in the same network and scan with Zeroconf
- The device has a new IP and ID

It is possible to have multiple devices with the same name.
I need to identify the device due to it's unique hostname / dns name to communicate with the correct device.

**Comment by onovotny** [comment]
I'm still not sure there's any good solution to this. The device name and IP are the only things that could be relied on unless it specifically returns something stable. IP's do change, though the hostname's less-so.

A typical approach is to store the hostname and then rescan to get the device's current IP based on the known hostname value.

**Comment by SebastianBone** [comment]
That is exactly what I want to do, but the ID / Hostname changes with the IP-address.

Screenshot 1: Shows Zeroconf result of the device. The ID has changed with the IP.
![zeroconf](https://user-images.githubusercontent.com/5979777/33611642-6a4d8ce2-d9cf-11e7-9604-cc26cacf04cd.png)

Screenshot 2: First line shows the same device with Host- / DNS-name
<img width="1284" alt="debookee" src="https://user-images.githubusercontent.com/5979777/33611648-6e758fae-d9cf-11e7-8754-e3e2cba24344.png">

**Comment by clairernovotny** [comment]
Closing due to age. Open to ideas and PR if still applicable.
