### ISSUE TITLE
Expriencing a timing issue on ZeroConfResolver.ResolveAsync method

### ISSUE THREAD

**Issue by mauroa** [novotnyllc/Zeroconf#95]
Hi,
I'm seeing a strange behavior when calling `ZeroConfResolver.ResolveAsync`, given that the result of the call retrieves an empty `IReadonlyList<IZeroConfHost>`, while the callback passed to the method argument (`Action<IZeroCongHost>`) is getting me correct results.

This is the basic code that I'm testing in a console app:

 ` var protocol = "_ssh._tcp.local.";`
   `var resolvedHosts = await ZeroconfResolver`
      `.ResolveAsync(protocol , callback: host => Console.WriteLine($"Discovered Host: {host.DisplayName}"))`
     ` .ConfigureAwait(false);`

  `Console.WriteLine($"Resolved Hosts: {string.Join(", ", resolvedHosts.Select(host => host.DisplayName))}");`

Now, the Console App output is:

"Discovered Host: foo MacBook Pro"
"Resolved Hosts: "

The curious thing is that If I put a Breakpoint in the callback Action and I wait some time, then the `ResolveAsync` method returns the correct results.

**Comment by onovotny** [comment]
What version of Zeroconf is it?

**Comment by mauroa** [comment]
Hi, it's Zeroconf 2.9.0

**Comment by clairernovotny** [comment]
Closing due to age. Please re-open if still an issue.
